version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: association_test_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - association-network

  backend:
    build: ./backend
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=association_test_db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - association-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - association-network

networks:
  association-network:
    driver: bridge

volumes:
  postgres-data:
