name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          POSTGRES_DB: association_db
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run backend tests
      working-directory: ./backend
      run: npm test

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Run frontend build
      working-directory: ./frontend
      run: npm run build

    - name: Lint frontend
      working-directory: ./frontend
      run: npm run lint
